CREATE DATABASE IF NOT EXISTS gkk_auth_db;
CREATE DATABASE IF NOT EXISTS gkk_vendor_db;
CREATE DATABASE IF NOT EXISTS gkk_menu_db;
CREATE DATABASE IF NOT EXISTS gkk_order_db;
CREATE DATABASE IF NOT EXISTS gkk_payment_db;
